# Generated by Django 5.1 on 2024-09-10 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Марка')),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.TextField(verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.TextField(verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='car',
            name='mark_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.mark'),
        ),
    ]
