# Generated by Django 5.1 on 2024-09-24 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_mark_options_remove_car_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Класс автомобиля')),
            ],
            options={
                'verbose_name': 'Класс автомобиля',
                'verbose_name_plural': 'Классы автомобиля',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carclass'),
        ),
    ]
