# Generated by Django 5.1 on 2024-09-24 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carclass_car_car_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Тип кузова автомобиля')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузова',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.bodytype'),
        ),
    ]
