# Generated by Django 5.1 on 2024-09-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_bodytype_car_body_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Страна производства автомобиля')),
            ],
            options={
                'verbose_name': 'Страна производства',
                'verbose_name_plural': 'Страны производства',
            },
        ),
    ]
