# Generated by Django 5.1 on 2024-10-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_car_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="picture",
            field=models.ImageField(
                null=True, upload_to="cars", verbose_name="Изображение"
            ),
        ),
    ]
