# Generated by Django 5.1 on 2024-10-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_car_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodytype",
            name="picture",
            field=models.ImageField(
                null=True, upload_to="bodyTypes", verbose_name="Изображение"
            ),
        ),
    ]
