# Generated by Django 5.1 on 2024-12-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0011_car_username_alter_car_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(verbose_name="Имя пользователя")),
                (
                    "picture",
                    models.ImageField(
                        null=True, upload_to="usersPhoto", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография пользователя",
                "verbose_name_plural": "Фотографии пользователей",
            },
        ),
        migrations.RemoveField(
            model_name="car",
            name="username",
        ),
    ]
